[environments]
  [environments.development]
    name = "aksengine"
    namespace = "chat"
    wait = true
    watch = false
    watch-delay = 2
    auto-connect = false
    dockerfile = "Dockerfile"
    chart = ""
